### ISSUE TITLE
feat: Should support a Spotify login. 

### ISSUE THREAD

**Issue by harshsbhat** [Arinji2/vibeify#1]
Considering this app revolves around Spotify. It would be beneficial to have a Spotify Auth option.

![image](https://github.com/user-attachments/assets/94e193d3-9b5c-4218-b736-a9c4816898d0)

**Comment by Arinji2** [comment]
Hiya, i decided to not go with a spotify login since i am going to force people to login with spotify as well once i decide to add features which need access to private repos. At the moment vibeify can do all of its work with just access to public playlists :D
